### ISSUE TITLE
Vertical?

### ISSUE THREAD

**Issue by uzman** [TMSantos/echantedviewpager#1]
hi,
is there a way to make it vertical?
thanks...

**Comment by TMSantos** [comment]
You can with some workarounds. This is more related to "customizing" ViewPager than this library itself. You can see ideias/methods to achieve this here for example: http://stackoverflow.com/a/22797619/1590791

What you would do ,is something like this:

```
 EnchantedViewPager mViewPager = (EnchantedViewPager) findViewById(R.id.viewpager);
mViewPager.setPageTransformer(true, new VerticalPageTransformer());  
```
VerticalPageTransformer code can be found at stackoverflow link

**Comment by uzman** [comment]
it would be good if there is a property like viewPager.setOrientation(VERTICAL / HORIZONTAL).

**Comment by TMSantos** [comment]
This is related to transformers, not in the scope/context of the library, you can just use the solution I provided above, closing
