### ISSUE TITLE
Not supporting high resolution screen

### ISSUE THREAD

**Issue by foram-patel** [TMSantos/echantedviewpager#2]
![test2](https://cloud.githubusercontent.com/assets/17020084/26518786/4a9c284a-42d5-11e7-95a5-96fd67c129c0.png)
![test1](https://cloud.githubusercontent.com/assets/17020084/26518787/4aa41c12-42d5-11e7-9e9d-dcdb0aa5c779.png)

I am really not getting why same library code gives different result in two different devices

First one is screenshot of Samsung galaxy on nxt (Resolution : 1080x1920 pixels)

Second one is screenshot of Huawei Nexus 6P (Resolution : 1440 x 2560 pixels)

Please help me to resolve this issue...

**Comment by TMSantos** [comment]
Hey foram-patel,

This doesnt seem to be a problem with the library, the library extends native SDK widget ViewPager and work as it.

You sure you are handling it properly? no static values at layout_height etc? Can you share your xml?

**Comment by foram-patel** [comment]
Hey TMSantos,

Thanks for the reply to my problem as you are saying there is no issue with library so let me check my entire xml code once again and if i will not get the solution i will sure take your help by sharing my xml with you...

Thank you
