### ISSUE TITLE
Loop and auto scroll

### ISSUE THREAD

**Issue by tellfa** [TMSantos/echantedviewpager#3]
How can i set auto scroll and loop mode for your viewpager?

**Comment by TMSantos** [comment]
You mean "carrossel" mode? You can't for now, I will add it as soon as I have some free time

**Comment by mseroczynski** [comment]
Any updates?

**Comment by tellfa** [comment]
@TMSantos , why not update this library for set loop ?

**Comment by TMSantos** [comment]
hey @tellfa , mostly due to lack of time, I implemented carrossel for it but the testing didn't went like I wanted, I promise I will try to look at it this week and provide a new release soon

**Comment by tellfa** [comment]
thanks my dear friend. please update soon because really we need this feature . thanks   ❤️

**Comment by TMSantos** [comment]
@tellfa @mseroczynski I updated the library to v1.1.0

It contains the carrossel/infinite loop , sry for the wait :p

Check the README for more information.
