### ISSUE TITLE
carousel/infinite loop mode not working

### ISSUE THREAD

**Issue by lyrathaprinces** [TMSantos/echantedviewpager#4]
hi,, as per documentation,,,for achieving carousel ,,,
i have not implemented getCount() method and used this line
 echantedAdapter.enableCarrousel();
but i am not able to make carousel working?

**Comment by TMSantos** [comment]
Hi @lyrathaprinces , without seeing your code is hard to help, I suggest to check the sample and follow carefully if something is missing

**Comment by TMSantos** [comment]
Closing, OP seems away
